import React, { createContext, useState, useEffect } from 'react';

export const ThemeLanguageContext = createContext();

const translations = {
    en: {
        dashboard: "Dashboard",
        admin_console: "Admin Console",
        recent_meetings: "Recent Meetings",
        sign_out: "Sign Out",
        welcome: "Welcome",
        manage_meetings: "Manage your meetings and communication.",
        new_meeting: "New Meeting",
        start_instant: "Start an instant meeting with your team.",
        meeting_topic: "Meeting Topic (Optional)",
        start_meeting: "Start Meeting",
        starting: "Starting...",
        join_meeting: "Join Meeting",
        enter_code: "Enter a meeting code or link to join.",
        meeting_id_link: "Meeting ID or Link",
        join_now: "Join Now",
        schedule: "Schedule",
        plan_future: "Plan a meeting for a future date.",
        coming_soon: "Coming Soon",
        overview: "Overview",
        users: "Users",
        meetings: "Meetings",
        back_to_app: "Back to App",
        total_users: "Total Users",
        active_meetings: "Active Meetings",
        host_nodes: "Host Nodes",
        participants: "Participants",
        add_user: "Add User",
        name_email: "Name & Email",
        role: "Role",
        status: "Status",
        actions: "Actions",
        meeting_title_id: "Meeting Title & ID",
        host: "Host",
        date: "Date",
        welcome_back: "Welcome Back",
        network_email: "Email Address",
        security_key: "Password",
        initiate_login: "Sign In",
        join_as_guest: "Join as Guest",
        new_instance: "New Instance?",
        register_directory: "Register Directory",
        create_identity: "Create Identity",
        join_network: "Join the communication network",
        full_identity_name: "Full Name",
        register_node: "Register Node",
        already_registered: "Already Registered?",
        sign_in_protocol: "Sign In Protocol",
        profile: "Profile",
        save_changes: "Save Changes",
        // Auth specific
        login_title: "Log in to Account",
        register_title: "Create Account",
        username: "Username",
        remember_me: "Remember",
        forgot_password: "Forgot?",
        or_continue_with: "or continue with",
        social: "Social",
        guest_mode: "Guest Mode",
        hello_friend: "Hello, Friend!",
        welcome_back_title: "Welcome Back!",
        login_desc: "Enter your personal details and start your journey with us today.",
        register_desc: "To keep connected with us please login with your personal info.",
        accept_terms: "Accept Terms",
        home: "Home",
        back: "Back",
        enter_details: "Please enter your details",
        create_free_account: "Create your free account",
        // Toasts & confirms
        confirm_delete_meeting: "Are you sure you want to delete this meeting?",
        meeting_deleted: "Meeting deleted",
        action_failed: "Action failed",
        pw_required_private: "Password is required for private rooms",
        pw_not_allowed_public: "Public rooms cannot have password protection",
        // Password strength
        pw_weak: "Weak",
        pw_fair: "Fair",
        pw_good: "Good",
        pw_strong: "Strong",
        // Room events
        kicked_msg: "You have been removed from the meeting.",
        blocked_msg: "You have been permanently blocked from this meeting.",
        meeting_ended_msg: "Host has ended the meeting for everyone.",
        host_denied_share: "Host denied your request to share.",
        host_stopped_share: "Host has stopped your screen sharing.",
        meeting_not_found: "Meeting not found.",
        record_host_only: "Only the meeting host can record the meeting.",
        chat_disabled: "Chat is disabled for this room.",
        confirm_send_file: "Do you want to send this file?",
        confirm_delete_msg: "Are you sure you want to delete this message?",
        confirm_kick: "Are you sure you want to kick this user?",
        confirm_block: "Are you sure you want to BLOCK this user? They will not be able to rejoin.",
        confirm_end_meeting: "Are you sure you want to end the meeting for everyone?",
        confirm_guest_login: "Guests cannot perform this action. Would you like to log in or register?",
        // Bottom controls
        ctl_mute: "Mute",
        ctl_unmute: "Unmute",
        ctl_start_video: "Start Video",
        ctl_stop_video: "Stop Video",
        ctl_share: "Share",
        ctl_stop_share: "Stop",
        ctl_record: "Record",
        ctl_stop_record: "Stop",
        ctl_raise: "Raise",
        ctl_raise_hand: "Raise hand",
        ctl_settings: "Settings",
        ctl_chat: "Chat",
        ctl_people: "People",
        ctl_leave: "Leave",
        ctl_more: "More",
        ctl_meeting_id: "Meeting ID",
        ctl_copied: "Copied!",
        ctl_share_screen: "Share screen",
        ctl_stop_sharing: "Stop sharing",
        ctl_start_recording: "Start recording",
        ctl_stop_recording: "Stop recording",
        ctl_unmute_hold: "Unmute (hold to talk)",
        // Leave dialog
        leave_confirm: "Leave the meeting?",
        leave_only_me: "Leave meeting",
        leave_only_me_sub: "Others can keep going",
        leave_end_all: "End for everyone",
        leave_end_all_sub: "Closes the room and removes everyone",
        // Participants panel
        find_participant: "Find participant...",
        you_label: "You",
        mute_everyone: "Mute Everyone",
        role_host: "Host",
        role_cohost: "Co-host",
        role_participant: "Participant",
        role_guest: "Guest",
        // Chat
        chat_empty_title: "No messages yet",
        chat_empty_sub: "Start the conversation!",
        chat_input_placeholder: "Type a message...",
        chat_input_edit_placeholder: "Edit message...",
        chat_close: "Close",
        chat_send: "Send",
        chat_edit: "Edit",
        chat_delete: "Delete",
        chat_attach: "Attach file",
        chat_download: "Download",
        chat_today: "Today",
        chat_send_hint: "Enter — send",
        // Screen share toasts
        share_unsupported: "This browser does not support screen sharing.",
        share_busy: "{name} is currently sharing the screen.",
        share_failed: "Could not start screen sharing.",
        // Misc
        cancel: "Cancel",
    },
    uz: {
        dashboard: "Boshqaruv paneli",
        admin_console: "Admin panel",
        recent_meetings: "So'nggi uchrashuvlar",
        sign_out: "Chiqish",
        welcome: "Xush kelibsiz",
        manage_meetings: "Uchrashuv va muloqotlarni boshqaring.",
        new_meeting: "Yangi uchrashuv",
        start_instant: "Jamoangiz bilan tezkor uchrashuv boshlash.",
        meeting_topic: "Uchrashuv mavzusi (Ixtiyoriy)",
        start_meeting: "Boshlash",
        starting: "Boshlanmoqda...",
        join_meeting: "Uchrashuvga qo'shilish",
        enter_code: "Qo'shilish uchun kod yoki havolani kiriting.",
        meeting_id_link: "ID yoki Havola",
        join_now: "Qo'shilish",
        schedule: "Rejalashtirish",
        plan_future: "Kelajakdagi uchrashuvni rejalashtirish.",
        coming_soon: "Tez orada",
        overview: "Umumiy",
        users: "Foydalanuvchilar",
        meetings: "Uchrashuvlar",
        back_to_app: "Ilovaga qaytish",
        total_users: "Jami foydalanuvchilar",
        active_meetings: "Faol uchrashuvlar",
        host_nodes: "Xostlar",
        participants: "Ishtirokchilar",
        add_user: "Foydalanuvchi qo'shish",
        name_email: "Ism va Email",
        role: "Rol",
        status: "Holat",
        actions: "Harakatlar",
        meeting_title_id: "Uchrashuv nomi & ID",
        host: "Xost",
        date: "Sana",
        welcome_back: "Xush kelibsiz",
        network_email: "Email manzil",
        security_key: "Parol",
        initiate_login: "Kirish",
        join_as_guest: "Mehmon bo'lib qo'shilish",
        new_instance: "Ro'yxatdan o'tmaganmisiz?",
        register_directory: "Ro'yxatdan o'tish",
        create_identity: "Hisob yaratish",
        join_network: "Muloqot tarmog'iga qo'shiling",
        full_identity_name: "To'liq ism",
        register_node: "Ro'yxatdan o'tish",
        already_registered: "Hisobingiz bormi?",
        sign_in_protocol: "Kirish",
        profile: "Profil",
        save_changes: "Saqlash",
        // Auth specific
        login_title: "Tizimga kirish",
        register_title: "Hisob yaratish",
        username: "Foydalanuvchi nomi",
        remember_me: "Eslab qolish",
        forgot_password: "Unutdingizmi?",
        or_continue_with: "yoki davom eting",
        social: "Ijtimoiy",
        guest_mode: "Mehmon rejimi",
        hello_friend: "Salom, do'stim!",
        welcome_back_title: "Xush kelibsiz!",
        login_desc: "Shaxsiy ma'lumotlaringizni kiriting va bugun biz bilan sayohatingizni boshlang.",
        register_desc: "Biz bilan bog'lanib turish uchun shaxsiy ma'lumotlaringiz orqali kiring.",
        accept_terms: "Shartlarga roziman",
        home: "Bosh sahifa",
        back: "Orqaga",
        enter_details: "Ma'lumotlarni kiriting",
        create_free_account: "Bepul hisob yarating",
        confirm_delete_meeting: "Ushbu uchrashuvni o'chirmoqchimisiz?",
        meeting_deleted: "Uchrashuv o'chirildi",
        action_failed: "Amal bajarilmadi",
        pw_required_private: "Shaxsiy xonalar uchun parol kerak",
        pw_not_allowed_public: "Ommaviy xonalar parol bilan himoyalanmaydi",
        pw_weak: "Zaif",
        pw_fair: "O'rtacha",
        pw_good: "Yaxshi",
        pw_strong: "Kuchli",
        kicked_msg: "Siz uchrashuvdan chiqarib yuborildingiz.",
        blocked_msg: "Siz bu uchrashuvdan doimiy ravishda bloklangansiz.",
        meeting_ended_msg: "Xost uchrashuv tugundi.",
        host_denied_share: "Xost ulashish so'rovingizni rad etdi.",
        host_stopped_share: "Xost ekran ulashishingizni to'xtatdi.",
        meeting_not_found: "Uchrashuv topilmadi.",
        record_host_only: "Faqat xost yozib olishi mumkin.",
        chat_disabled: "Ushbu xonada chat o'chirib qo'yilgan.",
        confirm_send_file: "Bu faylni yubormoqchimisiz?",
        confirm_delete_msg: "Bu xabarni o'chirmoqchimisiz?",
        confirm_kick: "Bu foydalanuvchini chiqarib yubormoqchimisiz?",
        confirm_block: "Bu foydalanuvchini bloklaysizmi? Ular qayta kira olmaydi.",
        confirm_end_meeting: "Barcha uchun uchrashuvni tugatmoqchimisiz?",
        confirm_guest_login: "Mehmonlar bu amalni bajara olmaydi. Tizimga kirmoqchimisiz?",
        ctl_mute: "Mikrofonni o'chir",
        ctl_unmute: "Yoqish",
        ctl_start_video: "Kamerani yoq",
        ctl_stop_video: "Kamerani o'chir",
        ctl_share: "Ulashish",
        ctl_stop_share: "To'xtatish",
        ctl_record: "Yozib olish",
        ctl_stop_record: "To'xtatish",
        ctl_raise: "Qo'l",
        ctl_raise_hand: "Qo'l ko'tarish",
        ctl_settings: "Sozlamalar",
        ctl_chat: "Chat",
        ctl_people: "Ishtirokchilar",
        ctl_leave: "Chiqish",
        ctl_more: "Yana",
        ctl_meeting_id: "Uchrashuv ID",
        ctl_copied: "Nusxalandi!",
        ctl_share_screen: "Ekran ulashish",
        ctl_stop_sharing: "Ulashishni to'xtatish",
        ctl_start_recording: "Yozib olishni boshlash",
        ctl_stop_recording: "Yozib olishni to'xtatish",
        ctl_unmute_hold: "Yoqish (ushlab gapiring)",
        leave_confirm: "Xonadan chiqasizmi?",
        leave_only_me: "Faqat o'zim chiqaman",
        leave_only_me_sub: "Boshqalar davom ettira oladi",
        leave_end_all: "Hammaga tugatish",
        leave_end_all_sub: "Xonani yopadi va barchani chiqaradi",
        find_participant: "Ishtirokchi qidirish...",
        you_label: "Siz",
        mute_everyone: "Hammani o'chirish",
        role_host: "Xost",
        role_cohost: "Hammuallif",
        role_participant: "Ishtirokchi",
        role_guest: "Mehmon",
        chat_empty_title: "Hali xabar yo'q",
        chat_empty_sub: "Jamoangiz bilan muloqotni boshlang!",
        chat_input_placeholder: "Xabar yozing...",
        chat_input_edit_placeholder: "Xabarni tahrirlang...",
        chat_close: "Yopish",
        chat_send: "Yuborish",
        chat_edit: "Tahrirlash",
        chat_delete: "O'chirish",
        chat_attach: "Fayl biriktirish",
        chat_download: "Yuklab olish",
        chat_today: "Bugun",
        chat_send_hint: "Enter — yuborish",
        share_unsupported: "Bu brauzer ekran ulashishni qo'llab-quvvatlamaydi.",
        share_busy: "{name} hozir ekranini ulashmoqda.",
        share_failed: "Ekran ulashishni boshlab bo'lmadi.",
        cancel: "Bekor",
    },
    ru: {
        dashboard: "Панель управления",
        admin_console: "Консоль админа",
        recent_meetings: "Недавние встречи",
        sign_out: "Выйти",
        welcome: "Добро пожаловать",
        manage_meetings: "Управляйте встречами и общением.",
        new_meeting: "Новая встреча",
        start_instant: "Начать мгновенную встречу с командой.",
        meeting_topic: "Тема встречи (Необязательно)",
        start_meeting: "Начать встречу",
        starting: "Запуск...",
        join_meeting: "Присоединиться",
        enter_code: "Введите код или ссылку для подключения.",
        meeting_id_link: "ID встречи или ссылка",
        join_now: "Присоединиться",
        schedule: "Запланировать",
        plan_future: "Запланировать встречу на будущее.",
        coming_soon: "Скоро",
        overview: "Обзор",
        users: "Пользователи",
        meetings: "Встречи",
        back_to_app: "Вернуться в приложение",
        total_users: "Всего пользователей",
        active_meetings: "Активные встречи",
        host_nodes: "Организаторы",
        participants: "Участники",
        add_user: "Добавить",
        name_email: "Имя и Email",
        role: "Роль",
        status: "Статус",
        actions: "Действия",
        meeting_title_id: "Название & ID",
        host: "Организатор",
        date: "Дата",
        welcome_back: "С возвращением",
        network_email: "Электронная почта",
        security_key: "Пароль",
        initiate_login: "Войти",
        join_as_guest: "Войти как гость",
        new_instance: "Нет аккаунта?",
        register_directory: "Зарегистрироваться",
        create_identity: "Создать аккаунт",
        join_network: "Присоединяйтесь к сети",
        full_identity_name: "Полное имя",
        register_node: "Зарегистрироваться",
        already_registered: "Уже есть аккаунт?",
        sign_in_protocol: "Войти",
        profile: "Профиль",
        save_changes: "Сохранить изменения",
        // Auth specific
        login_title: "Вход в аккаунт",
        register_title: "Создать аккаунт",
        username: "Имя пользователя",
        remember_me: "Запомнить",
        forgot_password: "Забыли?",
        or_continue_with: "или продолжить через",
        social: "Соцсети",
        guest_mode: "Гостевой режим",
        hello_friend: "Привет, друг!",
        welcome_back_title: "С возвращением!",
        login_desc: "Введите свои данные и начните путешествие с нами сегодня.",
        register_desc: "Чтобы оставаться на связи, пожалуйста, войдите под своими данными.",
        accept_terms: "Принимаю условия",
        home: "Главная",
        back: "Назад",
        enter_details: "Введите свои данные",
        create_free_account: "Создайте бесплатный аккаунт",
        confirm_delete_meeting: "Вы уверены, что хотите удалить эту встречу?",
        meeting_deleted: "Встреча удалена",
        action_failed: "Действие не выполнено",
        pw_required_private: "Для приватных комнат требуется пароль",
        pw_not_allowed_public: "Публичные комнаты не должны быть защищены паролем",
        pw_weak: "Слабый",
        pw_fair: "Средний",
        pw_good: "Хороший",
        pw_strong: "Сильный",
        kicked_msg: "Вас удалили из встречи.",
        blocked_msg: "Вы навсегда заблокированы в этой встрече.",
        meeting_ended_msg: "Организатор завершил встречу.",
        host_denied_share: "Организатор отклонил ваш запрос на демонстрацию.",
        host_stopped_share: "Организатор остановил вашу демонстрацию экрана.",
        meeting_not_found: "Встреча не найдена.",
        record_host_only: "Только организатор может записывать встречу.",
        chat_disabled: "Чат отключён в этой комнате.",
        confirm_send_file: "Вы хотите отправить этот файл?",
        confirm_delete_msg: "Вы уверены, что хотите удалить это сообщение?",
        confirm_kick: "Вы уверены, что хотите выгнать этого пользователя?",
        confirm_block: "Заблокировать этого пользователя? Он не сможет вернуться.",
        confirm_end_meeting: "Завершить встречу для всех?",
        confirm_guest_login: "Гости не могут выполнять это действие. Хотите войти или зарегистрироваться?",
        ctl_mute: "Выкл. микрофон",
        ctl_unmute: "Включить",
        ctl_start_video: "Включить видео",
        ctl_stop_video: "Выкл. видео",
        ctl_share: "Демонстрация",
        ctl_stop_share: "Остановить",
        ctl_record: "Запись",
        ctl_stop_record: "Стоп",
        ctl_raise: "Рука",
        ctl_raise_hand: "Поднять руку",
        ctl_settings: "Настройки",
        ctl_chat: "Чат",
        ctl_people: "Участники",
        ctl_leave: "Выйти",
        ctl_more: "Ещё",
        ctl_meeting_id: "ID встречи",
        ctl_copied: "Скопировано!",
        ctl_share_screen: "Демонстрация экрана",
        ctl_stop_sharing: "Остановить демонстрацию",
        ctl_start_recording: "Начать запись",
        ctl_stop_recording: "Остановить запись",
        ctl_unmute_hold: "Включить (удерживайте)",
        leave_confirm: "Выйти из встречи?",
        leave_only_me: "Выйти только мне",
        leave_only_me_sub: "Другие смогут продолжить",
        leave_end_all: "Завершить для всех",
        leave_end_all_sub: "Закроет комнату для всех",
        find_participant: "Найти участника...",
        you_label: "Вы",
        mute_everyone: "Выключить у всех",
        role_host: "Организатор",
        role_cohost: "Соорганизатор",
        role_participant: "Участник",
        role_guest: "Гость",
        chat_empty_title: "Сообщений пока нет",
        chat_empty_sub: "Начните общение с командой!",
        chat_input_placeholder: "Напишите сообщение...",
        chat_input_edit_placeholder: "Редактировать сообщение...",
        chat_close: "Закрыть",
        chat_send: "Отправить",
        chat_edit: "Редактировать",
        chat_delete: "Удалить",
        chat_attach: "Прикрепить файл",
        chat_download: "Скачать",
        chat_today: "Сегодня",
        chat_send_hint: "Enter — отправить",
        share_unsupported: "Этот браузер не поддерживает демонстрацию экрана.",
        share_busy: "{name} сейчас демонстрирует экран.",
        share_failed: "Не удалось начать демонстрацию.",
        cancel: "Отмена",
    }
};

export const ThemeLanguageProvider = ({ children }) => {
    const [theme, setTheme] = useState(localStorage.getItem('theme') || 'light');
    const [lang, setLang] = useState(localStorage.getItem('lang') || 'uz');

    useEffect(() => {
        if (theme === 'dark') {
            document.documentElement.classList.add('dark');
        } else {
            document.documentElement.classList.remove('dark');
        }
        localStorage.setItem('theme', theme);
    }, [theme]);

    useEffect(() => {
        localStorage.setItem('lang', lang);
    }, [lang]);

    const toggleTheme = () => {
        setTheme(prev => prev === 'dark' ? 'light' : 'dark');
    };

    const changeLanguage = (newLang) => {
        setLang(newLang);
    };

    const t = (key) => {
        return translations[lang]?.[key] || translations['en'][key] || key;
    };

    return (
        <ThemeLanguageContext.Provider value={{ theme, toggleTheme, lang, changeLanguage, t }}>
            {children}
        </ThemeLanguageContext.Provider>
    );
};
